ae = ""
apply_t5_attn_mask = true
bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
caption_extension = ".txt"
clip_l = ""
discrete_flow_shift = 3.1582
dynamo_backend = "no"
epoch = 200
fp8_base = true
full_bf16 = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
guidance_scale = 1.0
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
logging_dir = ""
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_timestep = 1000
max_train_steps = 2000
mem_eff_save = true
min_bucket_reso = 256
mixed_precision = "bf16"
model_prediction_type = "raw"
network_alpha = 128
network_args = [ "train_double_block_indices=all", "train_single_block_indices=all",]
network_dim = 128
network_module = "networks.lora_flux"
noise_offset_type = "Original"
optimizer_args = [ "scale_parameter=False", "relative_step=False", "warmup_init=False", "weight_decay=0.01",]
optimizer_type = "Adafactor"
output_dir = ""
output_name = ""
pretrained_model_name_or_path = ""
prior_loss_weight = 1
resolution = "1024,1024"
sample_prompts = ""
sample_sampler = "euler_a"
save_every_n_epochs = 200
save_model_as = "safetensors"
save_precision = "float"
sdpa = true
seed = 1
t5xxl = ""
t5xxl_max_token_length = 512
text_encoder_lr = [ 5e-5, 5e-5,]
timestep_sampling = "sigmoid"
train_data_dir = ""
unet_lr = 5e-5
vae_batch_size = 4
wandb_run_name = ""
