services:
  ai-service:
    image: radiantjade/ehemo-app-training:final
    command: ["/bin/bash", "-c", "source venv/bin/activate && python -m ehemo"]
    volumes:
      - ./models/checkpoints:/app/ehemo/models/checkpoints
      - ./models/vae:/app/ehemo/models/vae
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
